### ISSUE TITLE
Crash when player leaves the "JoinGame" screen

### ISSUE THREAD

**Issue by Firstus** [grambas/guess-a-song#74]

**Comment by grambas** [comment]
Error:

 java.lang.NullPointerException: Attempt to invoke virtual method 'com.pubnub.api.PubNub isdp.guess_a_song.controller.PubNubClient.getPubnub()' on a null object reference
                                                                     at isdp.guess_a_song.ui.JoinGame$2.onClick(JoinGame.java:217)
                                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
